export const dummy_repos = [
  {
    repo_id: Math.random(),
    repo_name: "design-system",
    repo_type: "Public",
    repo_language: "JavaScript",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 1 day ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "codeant-ci-app",
    repo_type: "Private",
    repo_language: "Golang",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 2 days ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "analytics-dashboard",
    repo_type: "Public",
    repo_language: "Rust",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 4 days ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "mobile-app",
    repo_type: "Private",
    repo_language: "Python",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 1 day ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "e-commerce-platform",
    repo_type: "Public",
    repo_language: "Python",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 5 days ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "blog-website",
    repo_type: "Public",
    repo_language: "HTML/CSS",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 1 day ago",
  },
  {
    repo_id: Math.random(),
    repo_name: "social-network",
    repo_type: "Private",
    repo_language: "PHP",
    repo_size: "7320 KB",
    repo_date_updated: "Updated 6 days ago",
  },
];
